apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
